### ISSUE TITLE
docker-compose -f docker-compose-mainnet.yml up -d 不通过

### ISSUE THREAD

**Issue by OuterSpaceTears** [EOSpace/eos-sync#1]
执行下面这句话的时候报错
`docker-compose -f docker-compose-mainnet.yml up -d`

fzk@fzk-B250-HD3P:~/work/eos-sync$ sudo docker-compose -f docker-compose-mainnet.yml up -d
ERROR: Version in "./docker-compose-mainnet.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by noprom** [comment]
你的docker-compose版本是多少？
需要: docker-compose version >= 1.10.0

**Comment by OuterSpaceTears** [comment]
我的是1.8 我再试试

**Comment by noprom** [comment]
@OuterSpaceTears , 有问题吗，没问题可以关闭了
