### ISSUE TITLE
重启会出现nodeos启动失败 除非还是用init的脚本去启动，但这样就得重新开始同步。

### ISSUE THREAD

**Issue by hzqlmm** [EOSpace/eos-sync#3]
nodeosd_1  | 3311590ms thread-0   chain_plugin.cpp:208          plugin_initialize    ] initializing chain plugin
nodeosd_1  | 3311604ms thread-0   main.cpp:132                  main                 ] **database dirty flag set (likely due to unclean shutdown): replay required**
nodeosd_1  | 3311605ms thread-0   mongo_db_plugin.cpp:870       ~mongo_db_plugin_imp ] mongo_db_plugin shutdown in process please be patient this can take a few minutes

这个是什么原因呢？要怎么操作才能从上一次同步的区块继续同步呢

**Comment by noprom** [comment]
新增了重启和暂停的：
## Stop/Restart syncing
To stop the syncing process:
```
docker-compose -f docker-compose-mainnet-op.yml down
```
To restart the syncing process:
```
docker-compose -f docker-compose-mainnet-op.yml down
docker-compose -f docker-compose-mainnet-op.yml up -d
```

**Comment by noprom** [comment]
@hzqlmm 
没问题就关闭了。
