### ISSUE TITLE
automatic script fails

### ISSUE THREAD

**Issue by kstvigilante** [EOSpace/eos-sync#6]
i get the following error when i try to run the script
ERROR: for eos-sync_mongo_1  Cannot start service mongo: error while creating mount source path '/data/eos/nodeos-data-volume/nodeos-data-mainnet/mongo': mkdir /data: read-only file system

ERROR: for mongo  Cannot start service mongo: error while creating mount source path '/data/eos/nodeos-data-volume/nodeos-data-mainnet/mongo': mkdir /data: read-only file system
how to fix this????

**Comment by noprom** [comment]
What kind of cloud provider do you use?
You have to create there directories first.
